name: coq_dfs_always_retrieve_stack_machine
main_prompt: data/prompts/system/coq-proof-agent-with-dfs-always-retrieve-stack-machine.md
conv_prompt: data/prompts/conversation/coq-proof-agent-example-long-conv-dfs-always-retrieve.md
informal_proof_repo: