name: coq_dfs_no_retrieve
main_prompt: data/prompts/system/coq-proof-agent-with-dfs-no-retrieve.md
conv_prompt: data/prompts/conversation/coq-proof-agent-example-long-conv-dfs-no-retrieve.md
informal_proof_repo: