name: lean_few_shot_informal_miniF2F_test
main_prompt: data/prompts/baseline/simple-prompt-lean-informal.md
conv_prompt: data/prompts/baseline/simple-prompt-conv-lean-informal.md
informal_proof_repo: data/benchmarks/miniF2F/informal/test