name: lean_dfs_informal_gpt4_turbo
main_prompt: data/prompts/system/lean-proof-agent-with-dfs-and-informal.md
conv_prompt: data/prompts/conversation/lean-proof-agent-example-dfs-informal-multiple.md
informal_proof_repo: .log/proofs/informal-gpt-4-turbo-20240126-201808/informal_proofs