name: lean_few_shot_informal_to_formal_gpt4_turbo
main_prompt: data/prompts/baseline/simple-prompt-lean-informal-to-formal.md
conv_prompt: data/prompts/baseline/simple-prompt-conv-lean-informal-to-formal.md
informal_proof_repo: .log/proofs/eval_driver/informal_few_shot/gpt4/miniF2F_test/20231204-234547/informal_proofs