name: compcert_118_subset
num_files: 11
language: COQ
few_shot_data_path_for_retrieval: .log/tools/coq_raw_proofs/data/benchmarks/CompCert/2023-09-06-03-44-06/CompCert/train
few_shot_metadata_filename_for_retrieval: single.meta.json
dfs_data_path_for_retrieval: .log/run_data_generation_transforms/data/benchmarks/CompCert/train
dfs_metadata_filename_for_retrieval: local.meta.json
datasets:
  - project: data/benchmarks/CompCert
    files:
      - path: backend/Locations.v
        theorems:
          - slot_eq
          - eq
          - typesize_pos
          - typealign_pos
          - typealign_typesize
          - same_not_diff # In env Loc
          - diff_sym
          - disjoint_cons_left
          - disjoint_cons_right
          - gss # Locmap.gss
          - gss_reg # Locmap.gss_reg
          - getpair_exten # Locmap.getpair_exten
          - index_inj # Repeated twice in env IndexedTyp and IndexedSlot
          - eq_refl
          - eq_sym
          - eq_trans
          - lt_trans
      - path: backend/Selectionproof.v
        theorems:
          - set_optvar_lessdef
          - set_locals_lessdef
          - sel_builtin_res_correct
      - path: cfrontend/Cop.v
        theorems:
          - val_inject_vtrue
          - val_inject_vfalse
          - val_inject_of_bool
          - val_inject_vptrofs
          - notbool_bool_val
          - cast_idempotent
          - eq_int_type # In env ArithConv
          - typeconv_integer_promotion
      - path: common/Globalenvs.v
        theorems:
          - shift_symbol_address # Same theorem is repeated in multiple environments Senv and Genv, we prove it once only.
          - shift_symbol_address_32
          - shift_symbol_address_64
          # - Obligation4
          # - Obligation5
          # - Obligation6 these are unamed theorems so we just don't run on them Proverbot9001 runs on them
          - public_symbol_exists
          - find_funct_find_funct_ptr
          - find_funct_ptr_iff
          - find_var_info_iff
          - global_addresses_distinct
          - genv_next_add_globals
          - genv_public_add_globals
          - alloc_globals_app
          - init_data_size_addrof
      - path: MenhirLib/Validator_complete.v
        theorems:
          - is_validator_subset
      - path: flocq/Calc/Round.v
        theorems:
          - inbetween_int_NE
          - inbetween_int_NA
      - path: flocq/Core/Zaux.v
        theorems:
          - Zopp_le_cancel
          - Zgt_not_eq
          - Zpower_plus
          - Zpower_nat_S
          - Zsame_sign_trans_weak
          - radix_gt_0
          - Zsame_sign_imp
          - Zlt_bool_true
          - Zcompare_Lt
          - cond_Zopp_negb
          - abs_cond_Zopp
          - cond_Zopp_Zlt_bool
          - iter_nat_S
          - ZOmod_small_abs
          - Zcompare_Eq 
          - Zeq_bool_false
          - Zeq_bool_true
          - Zle_bool_false
          - Zle_bool_true
      - path: lib/Parmov.v
        theorems:
          - update_s
          - update_o
          - update_ident
          - update_twice
          - dests_append
          - dests_decomp
          - srcs_append
          - srcs_decomp
          - dests_disjoint_sym
          - dests_disjoint_cons_right
          - is_mill_cons
          - move_no_temp_append
          - is_path_pop
          - measure_decreasing_2
          - parmove_aux
          - parmove_dests_initial_reg_or_temp
          - parmove_srcs_initial_reg_or_temp
          - notin_dests_cons
          - exec_seq_app
          - env_equiv_refl
          - env_equiv_refl'
          - env_ext
          - exec_seq_rev_app
          - env_equiv_sym
          - env_equiv_trans
          - parmove2_wf_moves
          - no_overlap_sym
          - pairwise_disjoint_norepet
          - disjoint_temps_not_temp
          - mu_is_mill
          - no_overlap_pairwise
          - weak_exec_seq_match
      - path: x86/SelectOpproof.v
        theorems:
          - eval_Olea_ptr
          - eval_addrstack
          - eval_mulhs
          - eval_mulhu
          - eval_negf
          - eval_absf
          - eval_negfs
          - eval_absfs
          - eval_compf
          - eval_compfs
          - eval_singleoffloat
          - eval_floatofsingle
          - eval_intoffloat
          - eval_intofsingle
      - path: lib/Wfsimpl.v
        theorems:
          - unroll_Fixm
          - unroll_Fix
      - path: exportclight/Clightdefs.v
        theorems:
          - build_composite_env'