name: compcert_benchmark_hard
num_files: 13
language: COQ
few_shot_data_path_for_retrieval: .log/tools/coq_raw_proofs/data/benchmarks/CompCert/2023-09-06-03-44-06/CompCert/train
few_shot_metadata_filename_for_retrieval: single.meta.json
dfs_data_path_for_retrieval: .log/run_data_generation_transforms/data/benchmarks/CompCert/train
dfs_metadata_filename_for_retrieval: local.meta.json
datasets:
  - project: data/benchmarks/CompCert
    files:
      - path: MenhirLib/Validator_complete.v
        theorems: 
            - complete
            - complete_is_validator
            - is_validator_forall_items
            - is_validator_forall_lookahead_set
            - is_validator_forall_state_has_future
            - is_validator_iterate_lset
            - is_validator_state_has_future_subset
            - is_validator_subset
      - path: backend/Locations.v
        theorems: 
            - compare
            - diff_dec
            - diff_not_eq
            - diff_outside_interval
            - diff_sym
            - disjoint_cons_right
            - disjoint_notin
            - disjoint_sym
            - eq
            - getpair_exten
            - gpo
            - gso
            - gss
            - gss_reg
            - gss_typed
            - guo
            - gus
            - in_notin_diff
            - index_inj
            - lt_not_eq
            - lt_trans
            - norepet_dec
            - notin_dec
            - notin_disjoint
            - notin_iff
            - notin_not_in
            - outside_interval_diff
            - same_not_diff
            - typealign_pos
            - typealign_typesize
            - typesize_pos
      - path: backend/RTL.v
        theorems: 
            - exec_Iload'
            - exec_Iop'
            - max_pc_function_sound
            - max_reg_function_def
            - max_reg_function_params
            - max_reg_function_use
            - max_reg_instr_def
            - max_reg_instr_ge
            - max_reg_instr_uses
            - semantics_receptive
      - path: backend/Selectionproof.v
        theorems: 
            - HF'
            - TransfSelectionLink
            - call_cont_commut
            - classify_call_correct
            - classify_stmt_nolabel
            - classify_stmt_sound_1
            - classify_stmt_sound_2
            - classify_stmt_wt
            - eval_binop_lessdef
            - eval_condexpr_of_expr
            - eval_condition_of_expr
            - eval_load
            - eval_sel_binop
            - eval_sel_known_builtin
            - eval_sel_select
            - eval_sel_unop
            - eval_select_safe_exprs
            - eval_store
            - eval_unop_lessdef
            - expr_is_addrof_ident_correct
            - find_label_commut
            - functions_translated
            - get_helpers_correct
            - helper_functions_declared_linkorder
            - helper_functions_preserved
            - if_conversion_base_nolabel
            - if_conversion_correct
            - if_conversion_nolabel
            - lookup_helper_correct
            - lookup_helper_correct_1
            - match_is_call_cont
            - record_globdefs_sound
            - sel_builtin_arg_correct
            - sel_builtin_args_correct
            - sel_builtin_correct
            - sel_builtin_default_correct
            - sel_builtin_nolabel
            - sel_expr_correct
            - sel_exprlist_correct
            - sel_final_states
            - sel_initial_states
            - sel_select_opt_correct
            - sel_step_correct
            - sel_switch_correct
            - sel_switch_correct_rec
            - sel_switch_int_correct
            - sel_switch_long_correct
            - senv_preserved
            - set_locals_lessdef
            - set_params_lessdef
            - set_var_lessdef
            - sig_function_translated
            - stackspace_function_translated
            - transf_program_correct
            - transf_program_match
            - wt_prog
      - path: cfrontend/Cop.v
        theorems: 
            - bool_val_inj
            - bool_val_inject
            - cast_bool_bool_val
            - cast_int_int_idem
            - cast_val_casted
            - cast_val_is_casted
            - classify_binarith_arithmetic_conversion
            - eq_int_type
            - sem_binarith_inject
            - sem_binary_operation_inj
            - sem_binary_operation_inject
            - sem_cast_inj
            - sem_cast_inject
            - sem_cmp_inj
            - sem_cmp_ptr_inj
            - sem_shift_inject
            - sem_unary_operation_inj
            - sem_unary_operation_inject
            - typeconv_integer_promotion
            - val_casted_has_type
            - val_inject_vfalse
            - val_inject_vptrofs
            - val_inject_vtrue
      - path: common/Globalenvs.v
        theorems: 
            - add_global_match
            - add_globals_app
            - add_globals_ensures
            - add_globals_match
            - add_globals_norepet_ensures
            - add_globals_preserves
            - add_globals_unique_ensures
            - add_globals_unique_preserves
            - advance_next_le
            - alloc_global_exists
            - alloc_global_initialized
            - alloc_global_neutral
            - alloc_global_nextblock
            - alloc_global_perm
            - alloc_global_unchanged
            - alloc_globals_app
            - alloc_globals_initialized
            - alloc_globals_match
            - alloc_globals_neutral
            - alloc_globals_nextblock
            - alloc_globals_perm
            - alloc_globals_unchanged
            - block_is_volatile_below
            - find_def_inversion
            - find_def_match
            - find_def_not_fresh
            - find_def_symbol
            - find_funct_find_funct_ptr
            - find_funct_inv
            - find_funct_inversion
            - find_funct_match
            - find_funct_prop
            - find_funct_ptr_iff
            - find_funct_ptr_inversion
            - find_funct_ptr_match
            - find_funct_ptr_not_fresh
            - find_funct_ptr_prop
            - find_funct_ptr_transf
            - find_funct_ptr_transf_partial
            - find_funct_transf
            - find_funct_transf_partial
            - find_invert_symbol
            - find_symbol_exists
            - find_symbol_inversion
            - find_symbol_match
            - find_symbol_not_fresh
            - find_symbol_transf
            - find_symbol_transf_partial
            - find_var_info_iff
            - find_var_info_match
            - find_var_info_not_fresh
            - genv_next_add_globals
            - genv_public_add_globals
            - global_addresses_distinct
            - globalenv_public
            - globalenvs_match
            - in_norepet_unique
            - init_mem_characterization
            - init_mem_characterization_2
            - init_mem_characterization_gen
            - init_mem_exists
            - init_mem_genv_next
            - init_mem_inversion
            - init_mem_match
            - init_mem_transf
            - init_mem_transf_partial
            - initmem_inject
            - invert_find_symbol
            - load_store_init_data_invariant
            - read_as_zero_unchanged
            - senv_match
            - senv_transf
            - senv_transf_partial
            - shift_symbol_address
            - shift_symbol_address_32
            - shift_symbol_address_64
            - store_init_data_aligned
            - store_init_data_exists
            - store_init_data_list_aligned
            - store_init_data_list_charact
            - store_init_data_list_exists
            - store_init_data_list_free_idents
            - store_init_data_list_loadbytes
            - store_init_data_list_match
            - store_init_data_list_neutral
            - store_init_data_list_nextblock
            - store_init_data_list_perm
            - store_init_data_list_unchanged
            - store_init_data_loadbytes
            - store_init_data_neutral
            - store_init_data_perm
            - store_init_data_unchanged
            - store_zeros
            - store_zeros_exists
            - store_zeros_loadbytes
            - store_zeros_neutral
            - store_zeros_nextblock
            - store_zeros_perm
            - store_zeros_read_as_zero
            - store_zeros_unchanged
      - path: exportclight/Clightdefs.v
        theorems: 
            - build_composite_env'
      - path: flocq/Calc/Round.v
        theorems: 
            - cexp_inbetween_float
            - cexp_inbetween_float_loc_Exact
            - generic_format_truncate
            - inbetween_float_DN
            - inbetween_float_DN_sign
            - inbetween_float_NA
            - inbetween_float_NE
            - inbetween_float_NE_sign
            - inbetween_float_UP
            - inbetween_float_UP_sign
            - inbetween_float_ZR
            - inbetween_float_ZR_sign
            - inbetween_float_round
            - inbetween_float_round_sign
            - inbetween_int_DN
            - inbetween_int_DN_sign
            - inbetween_int_N
            - inbetween_int_NA_sign
            - inbetween_int_NE
            - inbetween_int_NE_sign
            - inbetween_int_N_sign
            - inbetween_int_UP
            - inbetween_int_UP_sign
            - inbetween_int_ZR
            - inbetween_int_ZR_sign
            - round_any_correct
            - round_sign_any_correct
            - round_trunc_any_correct
            - round_trunc_any_correct'
            - round_trunc_sign_any_correct
            - round_trunc_sign_any_correct'
            - truncate_0
            - truncate_FIX_correct
            - truncate_aux_comp
            - truncate_correct
            - truncate_correct'
            - truncate_correct_format
            - truncate_correct_partial
            - truncate_correct_partial'
      - path: flocq/Core/Zaux.v
        theorems: 
            - ZOdiv_mod_mult
            - ZOdiv_plus
            - ZOdiv_small_abs
            - ZOmod_eq
            - ZOmod_mod_mult
            - Zcompare_Gt
            - Zcompare_spec
            - Zdiv_eucl_unique
            - Zdiv_mod_mult
            - Zeq_bool_spec
            - Zeven_Zpower_odd
            - Zeven_ex
            - Zfast_div_eucl_correct
            - Zfast_pow_pos_correct
            - Zgt_not_eq
            - Zle_bool_spec
            - Zlt_bool_false
            - Zlt_bool_spec
            - Zmod_mod_mult
            - Zopp_le_cancel
            - Zpos_div_eucl_aux1_correct
            - Zpos_div_eucl_aux_correct
            - Zpower_Zpower_nat
            - Zpower_ge_0
            - Zpower_gt_0
            - Zpower_gt_1
            - Zpower_gt_id
            - Zpower_le
            - Zpower_lt
            - Zpower_lt_Zpower
            - Zpower_pos_gt_0
            - Zsame_sign_imp
            - Zsame_sign_odiv
            - Zsame_sign_trans
            - abs_cond_Zopp
            - cond_Zopp_Zlt_bool
            - cond_Zopp_negb
            - eqbool_irrelevance
            - iter_nat_S
            - iter_nat_plus
            - iter_pos_nat
            - negb_Zle_bool
            - negb_Zlt_bool
            - radix_gt_0
            - radix_gt_1
            - radix_val_inj
      - path: flocq/Prop/Mult_error.v
        theorems: 
            - F2R_ge
            - mult_bpow_exact_FLT
            - mult_bpow_exact_FLX
            - mult_error_FLT
            - mult_error_FLT_ge_bpow
            - mult_error_FLX
            - mult_error_FLX_aux
      - path: lib/Parmov.v
        theorems: 
            - dests_disjoint_append_left
            - dests_disjoint_append_right
            - dests_disjoint_cons_left
            - dests_disjoint_cons_right
            - dests_disjoint_sym
            - disjoint_list_notin
            - disjoint_temps_not_temp
            - dtransition_preserves_wf_state
            - dtransitions_correctness
            - dtransitions_preserve_wf_state
            - env_equiv_sym
            - env_equiv_trans
            - exec_par_append_eq
            - exec_par_combine
            - exec_par_env_equiv
            - exec_par_ident
            - exec_par_lift
            - exec_par_outside
            - exec_par_update_no_read
            - exec_seq_app
            - exec_seq_exec_seq_rev
            - exec_seq_rev_exec_seq
            - in_dests
            - in_srcs
            - is_last_source_charact
            - is_mill_append
            - is_mill_cons
            - is_path_change_last_source
            - measure_decreasing_1
            - move_no_temp_append
            - move_no_temp_rev
            - mu_is_mill
            - mu_move_no_temp
            - no_adherence_dst
            - no_adherence_src
            - no_adherence_tmp
            - no_overlap_pairwise
            - no_overlap_sym
            - no_read_path
            - notin_dests_append
            - notin_dests_cons
            - pairwise_disjoint_norepet
            - parmove2_correctness
            - parmove2_correctness_with_overlap
            - parmove2_wf_moves
            - parmove_aux_transitions
            - parmove_correctness
            - parmove_initial_reg_or_temp
            - parmove_preserves_register_classes
            - parmove_step_compatible
            - parmove_wf_moves
            - path_sources_dests
            - replace_last_source_charact
            - split_move_charact
            - srcs_dests_combine
            - state_wf_start
            - temp_last_change_last_source
            - temp_last_pop
            - temp_last_push
            - transition_determ
            - transition_preserves_semantics
            - transition_preserves_wf
            - transitions_correctness
            - transitions_determ
            - transitions_preserve_semantics
            - transitions_preserve_wf
            - update_commut
            - update_o
            - update_s
            - weak_exec_seq_match
            - weak_update_match
            - wf_move_initial_reg_or_temp
            - wf_moves_append
            - wf_moves_cons
      - path: lib/Wfsimpl.v
        theorems: 
            - unroll_Fix
      - path: x86/SelectOpproof.v
        theorems: 
            - eval_absf
            - eval_absfs
            - eval_add
            - eval_addf
            - eval_addfs
            - eval_addimm
            - eval_addressing
            - eval_addrstack
            - eval_addrsymbol
            - eval_and
            - eval_andimm
            - eval_builtin_arg
            - eval_builtin_arg_addr
            - eval_cast16signed
            - eval_cast16unsigned
            - eval_cast8signed
            - eval_cast8unsigned
            - eval_comp
            - eval_compf
            - eval_compfs
            - eval_compimm
            - eval_compimm_swap
            - eval_compu
            - eval_divs_base
            - eval_divu_base
            - eval_floatofint
            - eval_floatofintu
            - eval_floatofsingle
            - eval_intoffloat
            - eval_intofsingle
            - eval_intuoffloat
            - eval_intuofsingle
            - eval_mods_base
            - eval_modu_base
            - eval_mul
            - eval_mulf
            - eval_mulfs
            - eval_mulhs
            - eval_mulhu
            - eval_mulimm
            - eval_mulimm_base
            - eval_negf
            - eval_negfs
            - eval_negint
            - eval_notint
            - eval_or
            - eval_orimm
            - eval_platform_builtin
            - eval_same_expr
            - eval_select
            - eval_shl
            - eval_shlimm
            - eval_shr
            - eval_shrimm
            - eval_shru
            - eval_shruimm
            - eval_shrximm
            - eval_singleoffloat
            - eval_singleofint
            - eval_singleofintu
            - eval_sub
            - eval_subf
            - eval_subfs
            - eval_xor
            - eval_xorimm
            - int_add_sub_eq