name: mini_miniF2F_test_isabelle
num_files: 1
language: ISABELLE
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
timeout_per_theorem_in_secs: 1200
datasets:
  - project: data/benchmarks/miniF2F/isabelle/test
    files:
      - path: aime_1983_p2.thy
        theorems: "*"
      - path: aime_1989_p8.thy
        theorems: "*"
      - path: aime_1983_p1.thy
        theorems: "*"
      - path: algebra_sqineq_at2malt1.thy
        theorems: "*"
      - path: amc12a_2002_p6.thy
        theorems: "*"
      - path: amc12a_2013_p4.thy
        theorems: "*"
      - path: amc12a_2021_p9.thy
        theorems: "*"
      - path: amc12a_2021_p19.thy
        theorems: "*"
      - path: amc12b_2020_p6.thy
        theorems: "*"
      - path: amc12a_2009_p6.thy
        theorems: "*"
      - path: amc12b_2021_p4.thy
        theorems: "*"
      - path: imo_1959_p1.thy
        theorems: "*"
      - path: induction_pprime_pdvdapowpma.thy
        theorems: "*"
      - path: mathd_algebra_139.thy
        theorems: "*"
      - path: mathd_algebra_158.thy
        theorems: "*"
      - path: mathd_algebra_270.thy
        theorems: "*"
      - path: mathd_algebra_296.thy
        theorems: "*"
      - path: mathd_algebra_33.thy
        theorems: "*"
      - path: mathd_algebra_80.thy
        theorems: "*"
      - path: mathd_algebra_141.thy
        theorems: "*"
      - path: mathd_algebra_263.thy
        theorems: "*"
      - path: mathd_algebra_137.thy
        theorems: "*"
      - path: mathd_algebra_342.thy
        theorems: "*"
      - path: mathd_numbertheory_12.thy
        theorems: "*"
      - path: mathd_numbertheory_127.thy
        theorems: "*"
      - path: mathd_numbertheory_247.thy
        theorems: "*"
      - path: mathd_numbertheory_234.thy
        theorems: "*"
      - path: mathd_numbertheory_341.thy
        theorems: "*"
      - path: mathd_numbertheory_135.thy
        theorems: "*"
      - path: mathd_numbertheory_227.thy
        theorems: "*"
      - path: mathd_numbertheory_314.thy
        theorems: "*"
      - path: mathd_numbertheory_582.thy
        theorems: "*"
      - path: numbertheory_2pownm1prime_nprime.thy
        theorems: "*"
      - path: numbertheory_4x3m7y3neq2003.thy
        theorems: "*"

# Note: Chosen to be a representative sample of theorems from miniF2F (about 13% in size)
# To test new prompts. Split according to problems solved by COPRA