name: miniF2F_test_mathd_numbertheory
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - mathd_numbertheory_100
          - mathd_numbertheory_1124
          - mathd_numbertheory_12
          - mathd_numbertheory_127
          - mathd_numbertheory_135
          - mathd_numbertheory_150
          - mathd_numbertheory_175
          - mathd_numbertheory_185
          - mathd_numbertheory_207
          - mathd_numbertheory_212
          - mathd_numbertheory_222
          - mathd_numbertheory_227
          - mathd_numbertheory_229
          - mathd_numbertheory_233
          - mathd_numbertheory_234
          - mathd_numbertheory_235
          - mathd_numbertheory_237
          - mathd_numbertheory_239
          - mathd_numbertheory_247
          - mathd_numbertheory_254
          - mathd_numbertheory_277
          - mathd_numbertheory_293
          - mathd_numbertheory_296
          - mathd_numbertheory_299
          - mathd_numbertheory_3
          - mathd_numbertheory_314
          - mathd_numbertheory_320
          - mathd_numbertheory_321
          - mathd_numbertheory_328
          - mathd_numbertheory_34
          - mathd_numbertheory_341
          - mathd_numbertheory_342
          - mathd_numbertheory_343
          - mathd_numbertheory_345
          - mathd_numbertheory_353
          - mathd_numbertheory_427
          - mathd_numbertheory_430
          - mathd_numbertheory_435
          - mathd_numbertheory_447
          - mathd_numbertheory_451
          - mathd_numbertheory_457
          - mathd_numbertheory_483
          - mathd_numbertheory_495
          - mathd_numbertheory_5
          - mathd_numbertheory_517
          - mathd_numbertheory_521
          - mathd_numbertheory_541
          - mathd_numbertheory_551
          - mathd_numbertheory_552
          - mathd_numbertheory_559
          - mathd_numbertheory_582
          - mathd_numbertheory_618
          - mathd_numbertheory_66
          - mathd_numbertheory_711
          - mathd_numbertheory_728
          - mathd_numbertheory_764
          - mathd_numbertheory_765
          - mathd_numbertheory_769
          - mathd_numbertheory_85
          - mathd_numbertheory_99