name: miniF2F_lean4_test
num_files: 1
language: LEAN4
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/test/miniF2F-lean4
    files:
      - path: MiniF2F/Test.lean
        theorems: "*"

