name: miniF2F_test_proved_in_lean
num_files: 1
language: ISABELLE
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
timeout_per_theorem_in_secs: 1200
datasets:
  - project: data/benchmarks/miniF2F/isabelle/test
    files:
      - path: aime_1983_p2.thy
        theorems: "*"
      - path: aime_1989_p8.thy
        theorems: "*"
      - path: algebra_sqineq_at2malt1.thy
        theorems: "*"
      - path: amc12a_2002_p6.thy
        theorems: "*"
      - path: amc12a_2013_p4.thy
        theorems: "*"
      - path: amc12a_2021_p9.thy
        theorems: "*"
      - path: amc12b_2002_p19.thy
        theorems: "*"
      - path: amc12b_2002_p2.thy
        theorems: "*"
      - path: amc12b_2020_p2.thy
        theorems: "*"
      - path: amc12b_2020_p6.thy
        theorems: "*"
      - path: mathd_algebra_125.thy
        theorems: "*"
      - path: mathd_algebra_129.thy
        theorems: "*"
      - path: mathd_algebra_137.thy
        theorems: "*"
      - path: mathd_algebra_139.thy
        theorems: "*"
      - path: mathd_algebra_141.thy
        theorems: "*"
      - path: mathd_algebra_142.thy
        theorems: "*"
      - path: mathd_algebra_143.thy
        theorems: "*"
      - path: mathd_algebra_148.thy
        theorems: "*"
      - path: mathd_algebra_158.thy
        theorems: "*"
      - path: mathd_algebra_160.thy
        theorems: "*"
      - path: mathd_algebra_171.thy
        theorems: "*"
      - path: mathd_algebra_176.thy
        theorems: "*"
      - path: mathd_algebra_24.thy
        theorems: "*"
      - path: mathd_algebra_246.thy
        theorems: "*"
      - path: mathd_algebra_263.thy
        theorems: "*"
      - path: mathd_algebra_270.thy
        theorems: "*"
      - path: mathd_algebra_296.thy
        theorems: "*"
      - path: mathd_algebra_302.thy
        theorems: "*"
      - path: mathd_algebra_304.thy
        theorems: "*"
      - path: mathd_algebra_314.thy
        theorems: "*"
      - path: mathd_algebra_329.thy
        theorems: "*"
      - path: mathd_algebra_33.thy
        theorems: "*"
      - path: mathd_algebra_346.thy
        theorems: "*"
      - path: mathd_algebra_354.thy
        theorems: "*"
      - path: mathd_algebra_359.thy
        theorems: "*"
      - path: mathd_algebra_388.thy
        theorems: "*"
      - path: mathd_algebra_400.thy
        theorems: "*"
      - path: mathd_algebra_412.thy
        theorems: "*"
      - path: mathd_algebra_419.thy
        theorems: "*"
      - path: mathd_algebra_432.thy
        theorems: "*"
      - path: mathd_algebra_44.thy
        theorems: "*"
      - path: mathd_algebra_440.thy
        theorems: "*"
      - path: mathd_algebra_441.thy
        theorems: "*"
      - path: mathd_algebra_478.thy
        theorems: "*"
      - path: mathd_algebra_513.thy
        theorems: "*"
      - path: mathd_algebra_76.thy
        theorems: "*"
      - path: mathd_algebra_80.thy
        theorems: "*"
      - path: mathd_numbertheory_12.thy
        theorems: "*"
      - path: mathd_numbertheory_127.thy
        theorems: "*"
      - path: mathd_numbertheory_135.thy
        theorems: "*"
      - path: mathd_numbertheory_150.thy
        theorems: "*"
      - path: mathd_numbertheory_175.thy
        theorems: "*"
      - path: mathd_numbertheory_185.thy
        theorems: "*"
      - path: mathd_numbertheory_207.thy
        theorems: "*"
      - path: mathd_numbertheory_212.thy
        theorems: "*"
      - path: mathd_numbertheory_229.thy
        theorems: "*"
      - path: mathd_numbertheory_235.thy
        theorems: "*"
      - path: mathd_numbertheory_237.thy
        theorems: "*"
      - path: mathd_numbertheory_239.thy
        theorems: "*"
      - path: mathd_numbertheory_247.thy
        theorems: "*"
      - path: mathd_numbertheory_254.thy
        theorems: "*"
      - path: mathd_numbertheory_299.thy
        theorems: "*"
      - path: mathd_numbertheory_3.thy
        theorems: "*"
      - path: mathd_numbertheory_341.thy
        theorems: "*"
      - path: mathd_numbertheory_342.thy
        theorems: "*"
      - path: mathd_numbertheory_343.thy
        theorems: "*"
      - path: mathd_numbertheory_345.thy
        theorems: "*"
      - path: mathd_numbertheory_517.thy
        theorems: "*"
      - path: mathd_numbertheory_551.thy
        theorems: "*"
      - path: mathd_numbertheory_66.thy
        theorems: "*"
      - path: mathd_numbertheory_728.thy
        theorems: "*"
      - path: mathd_numbertheory_769.thy
        theorems: "*"
      - path: mathd_numbertheory_85.thy
        theorems: "*"