name: miniF2F_test_induction
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - induction_11div10tonmn1ton
          - induction_12dvd4expnp1p20
          - induction_1pxpownlt1pnx
          - induction_nfactltnexpnm1ngt3
          - induction_pord1p1on2powklt5on2
          - induction_pprime_pdvdapowpma
          - induction_prod1p1onk3le3m1onn
          - induction_sumkexp3eqsumksq