name: reprover_with_retrieval_neg
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - mathd_algebra_113
          - mathd_algebra_114
          - mathd_algebra_137
          - mathd_algebra_141
          - mathd_algebra_153
          - mathd_algebra_156
          - mathd_algebra_158
          - mathd_algebra_17
          - mathd_algebra_170
          - mathd_algebra_184
          - mathd_algebra_196
          - mathd_algebra_208
          - mathd_algebra_209
          - mathd_algebra_215
          - mathd_algebra_263
          - mathd_algebra_276
          - mathd_algebra_288
          - mathd_algebra_289
          - mathd_algebra_293
          - mathd_algebra_296
          - mathd_algebra_313
          - mathd_algebra_314
          - mathd_algebra_320
          - mathd_algebra_332
          - mathd_algebra_338
          - mathd_algebra_342
          - mathd_algebra_362
          - mathd_algebra_392
          - mathd_algebra_398
          - mathd_algebra_427
          - mathd_algebra_452
          - mathd_algebra_459
          - mathd_algebra_484
          - mathd_algebra_487
          - mathd_algebra_598
          - mathd_algebra_756
          - mathd_algebra_80
          - mathd_numbertheory_100
          - mathd_numbertheory_135
          - mathd_numbertheory_150
          - mathd_numbertheory_185
          - mathd_numbertheory_222
          - mathd_numbertheory_227
          - mathd_numbertheory_233
          - mathd_numbertheory_234
          - mathd_numbertheory_237
          - mathd_numbertheory_247
          - mathd_numbertheory_277
          - mathd_numbertheory_296
          - mathd_numbertheory_314
          - mathd_numbertheory_320
          - mathd_numbertheory_321
          - mathd_numbertheory_328
          - mathd_numbertheory_34
          - mathd_numbertheory_353
          - mathd_numbertheory_427
          - mathd_numbertheory_430
          - mathd_numbertheory_435
          - mathd_numbertheory_451
          - mathd_numbertheory_457
          - mathd_numbertheory_483
          - mathd_numbertheory_495
          - mathd_numbertheory_5
          - mathd_numbertheory_521
          - mathd_numbertheory_541
          - mathd_numbertheory_552
          - mathd_numbertheory_559
          - mathd_numbertheory_582
          - mathd_numbertheory_618
          - mathd_numbertheory_711
          - mathd_numbertheory_764
          - mathd_numbertheory_765
          - mathd_numbertheory_99
          - aime_1983_p1
          - aime_1983_p2
          - aime_1983_p3
          - aime_1984_p1
          - aime_1984_p7
          - aime_1987_p5
          - aime_1988_p8
          - aime_1990_p15
          - aime_1990_p4
          - aime_1991_p9
          - aime_1994_p3
          - aime_1995_p7
          - aime_1997_p9
          - aime_1999_p11
          - algebra_2varlineareq_fp3zeq11_3tfm1m5zeqn68_feqn10_zeq7
          - algebra_9onxpypzleqsum2onxpy
          - algebra_abpbcpcageq3_sumaonsqrtapbgeq3onsqrt2
          - algebra_absapbon1pabsapbleqsumabsaon1pabsa
          - algebra_absxm1pabsxpabsxp1eqxp2_0leqxleq1
          - algebra_amgm_sum1toneqn_prod1tonleq1
          - algebra_amgm_sumasqdivbgeqsuma
          - algebra_apbmpcneq0_aeq0anbeq0anceq0
          - algebra_apbon2pownleqapownpbpowon2
          - algebra_apbpceq2_abpbcpcaeq1_aleq1on3anbleq1ancleq4on3
          - algebra_bleqa_apbon2msqrtableqambsqon8b
          - algebra_cubrtrp1oncubrtreq3_rcubp1onrcubeq5778
          - algebra_ineq_nto1onlt2m1on
          - algebra_others_exirrpowirrrat
          - algebra_sqineq_at2malt1
          - algebra_sqineq_unitcircatbpabsamblt1
          - algebra_sqineq_unitcircatbpamblt1
          - algebra_sum1onsqrt2to1onsqrt10000lt198
          - amc12_2000_p1
          - amc12_2000_p12
          - amc12_2000_p20
          - amc12_2000_p6
          - amc12_2001_p21
          - amc12_2001_p5
          - amc12a_2002_p13
          - amc12a_2002_p6
          - amc12a_2003_p23
          - amc12a_2003_p5
          - amc12a_2008_p25
          - amc12a_2009_p6
          - amc12a_2009_p7
          - amc12a_2013_p4
          - amc12a_2019_p12
          - amc12a_2020_p10
          - amc12a_2020_p15
          - amc12a_2020_p25
          - amc12a_2020_p4
          - amc12a_2020_p7
          - amc12a_2020_p9
          - amc12a_2021_p12
          - amc12a_2021_p14
          - amc12a_2021_p18
          - amc12a_2021_p19
          - amc12a_2021_p22
          - amc12a_2021_p25
          - amc12a_2021_p3
          - amc12a_2021_p8
          - amc12b_2002_p19
          - amc12b_2002_p4
          - amc12b_2002_p7
          - amc12b_2020_p13
          - amc12b_2020_p21
          - amc12b_2020_p22
          - amc12b_2020_p6
          - amc12b_2021_p1
          - amc12b_2021_p13
          - amc12b_2021_p18
          - amc12b_2021_p3
          - amc12b_2021_p4
          - amc12b_2021_p9
          - imo_1959_p1
          - imo_1960_p2
          - imo_1962_p2
          - imo_1963_p5
          - imo_1964_p2
          - imo_1965_p2
          - imo_1968_p5_1
          - imo_1969_p2
          - imo_1974_p3
          - imo_1977_p6
          - imo_1981_p6
          - imo_1982_p1
          - imo_1983_p6
          - imo_1984_p6
          - imo_1985_p6
          - imo_1992_p1
          - imo_1997_p5
          - imo_2001_p6
          - imo_2019_p1
          - imosl_2007_algebra_p6
          - induction_11div10tonmn1ton
          - induction_12dvd4expnp1p20
          - induction_1pxpownlt1pnx
          - induction_nfactltnexpnm1ngt3
          - induction_pord1p1on2powklt5on2
          - induction_pprime_pdvdapowpma
          - induction_prod1p1onk3le3m1onn
          - induction_sumkexp3eqsumksq
          - numbertheory_2pownm1prime_nprime
          - numbertheory_3pow2pownm1mod2pownp3eq2pownp2
          - numbertheory_4x3m7y3neq2003
          - numbertheory_aoddbdiv4asqpbsqmod8eq1
          - numbertheory_exk2powkeqapb2mulbpa2_aeq1
          - numbertheory_fxeq4powxp6powxp9powx_f2powmdvdf2pown
          - numbertheory_notequiv2i2jasqbsqdiv8
          - numbertheory_x5neqy2p4