name: reprover_with_retrieval_hard
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - amc12a_2021_p9
          - mathd_algebra_107
          - mathd_algebra_270
          - mathd_algebra_275
          - mathd_algebra_302
          - mathd_algebra_329
          - mathd_algebra_33
          - mathd_algebra_440
          - mathd_numbertheory_1124
          - mathd_numbertheory_12
          - mathd_numbertheory_127
          - mathd_numbertheory_229
          - mathd_numbertheory_239
          - mathd_numbertheory_293
          - mathd_numbertheory_3
          - mathd_numbertheory_341
          - mathd_numbertheory_343
          - mathd_numbertheory_447