name: simple_benchmark_lean
num_files: 2
language: LEAN
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
timeout_per_theorem_in_secs: 600
datasets:
  - project: data/test/lean_proj
    files:
      - path: src/simple.lean
        theorems: "*"
        max_retry_attempts_limits:
          a_plus_b_b_plus_a: 1
          a_plus_zero: 1
          ab_square: 2
          mathd_algebra_478: 1
          mod_arith_1: 3
          n_less_2_pow_n: 3