name: simple_benchmark_1
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: .log/tools/coq_raw_proofs/data/test/coq/custom_group_theory/2023-09-06-03-32-37/theories/train
few_shot_metadata_filename_for_retrieval: single.meta.json
dfs_data_path_for_retrieval: .log/run_data_generation_transforms/data/test/custom_group_theory/train
dfs_metadata_filename_for_retrieval: local.meta.json
datasets:
  - project: data/test/coq/custom_group_theory/theories
    files:
      - path: grpthm.v
        theorems:
          - algb_identity_sum
          - algb_add_comm
          - algb_has_identity
          - associativity
          - algb_has_inverse
          - algb_is_closed
          - algb_is_abelian_group
          - algb_mul_is_closed
          - algb_mul_comm
          - algb_mul_assoc
          - algb_mul_add_distr