name: simple_benchmark_9
num_files: 9
language: COQ
few_shot_data_path_for_retrieval: .log/tools/coq_raw_proofs/data/test/coq/custom_group_theory/2023-09-06-03-32-37/theories/train
few_shot_metadata_filename_for_retrieval: single.meta.json
dfs_data_path_for_retrieval: .log/run_data_generation_transforms/data/test/custom_group_theory/train
dfs_metadata_filename_for_retrieval: local.meta.json
datasets:
  - project: data/test/coq/custom_group_theory/theories
    files:
      - path: grpthm.v
        theorems:
          - algb_identity_sum
          - algb_add_comm
          - algb_has_identity
          - associativity
          - algb_has_inverse
          - algb_is_closed
          - algb_is_abelian_group
          - algb_mul_is_closed
          - algb_mul_comm
          - algb_mul_assoc
          - algb_mul_add_distr
  - project: .
    files:
      - path: data/test/miniF2F-test/amc12_2001_p5.v
        theorems:
          - amc12_2001_p5
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_44_lvl4.v
        theorems:
          - mathd_algebra_44
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_141_lvl1.v
        theorems:
          - mathd_algebra_141
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_478_lvl1.v
        theorems:
          - mathd_algebra_478
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_numbertheory_207_lvl2.v
        theorems:
          - mathd_numbertheory_207
  - project: .
    files:
      - path: data/test/miniF2F-test/NEW_imo_1959_p1.v
        theorems:
          - imo_1959_p1
  - project: .
    files:
      - path: data/test/miniF2F-test/NEW_mathd_numbertheory_551_lvl1.v
        theorems:
          - mathd_numbertheory_551
  - project: .
    files:
      - path: data/test/miniF2F-test/numbertheory_4x3m7y3neq2003.v
        theorems:
          - numbertheory_4x3m7y3neq2003
  