name: simple_benchmark_lean4
num_files: 2
language: LEAN4
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
timeout_per_theorem_in_secs: 600
datasets:
  - project: data/test/lean4_proj
    files:
      - path: Lean4Proj/Temp.lean
        theorems: 
          - test
          - sq_ab