name: simple_benchmark_8
num_files: 8
language: COQ
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: .
    files:
      - path: data/test/miniF2F-test/amc12_2001_p5.v
        theorems:
          - amc12_2001_p5
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_44_lvl4.v
        theorems:
          - mathd_algebra_44
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_141_lvl1.v
        theorems:
          - mathd_algebra_141
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_algebra_478_lvl1.v
        theorems:
          - mathd_algebra_478
  - project: .
    files:
      - path: data/test/miniF2F-test/mathd_numbertheory_207_lvl2.v
        theorems:
          - mathd_numbertheory_207
  - project: .
    files:
      - path: data/test/miniF2F-test/NEW_imo_1959_p1.v
        theorems:
          - imo_1959_p1
  - project: .
    files:
      - path: data/test/miniF2F-test/NEW_mathd_numbertheory_551_lvl1.v
        theorems:
          - mathd_numbertheory_551
  - project: .
    files:
      - path: data/test/miniF2F-test/numbertheory_4x3m7y3neq2003.v
        theorems:
          - numbertheory_4x3m7y3neq2003
  