name: stack_machine_lean_hard
num_files: 2
language: LEAN4
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/test/stack_machine_lean
    files:
      - path: StackMachine/Theorems.lean
        theorems:
          - run_program_append
          - compile_preserves_stack
          - compile_correct