name: stack_machine_hard
num_files: 1
language: COQ
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: .
    files:
      - path: data/test/coq/stack_machine/StackMachine.v
        theorems:
          - compile_one_instr
          - compile_correct