defaults:
  - env_settings: bm25_retrieval
  - benchmark: miniF2F_lean4_test_imo
  - eval_settings: n_60_dfs_gpt4_o_no_retrieve_no_ex
  - prompt_settings: lean4_dfs
  - override hydra/job_logging: 'disabled'

eval_settings:
 timeout_in_secs: 600
 proof_retries: 25
 temperature: 1.2
 max_steps_per_episode: 100
 gpt_model_name: gpt-4o
#  gpt_model_name: gpt4-o
